#!/bin/sh /etc/rc.common
USE_PROCD=1
START=99

# ---------- EDIT ----------
MESHID='HOME-MESH'
MESHPASS='ChangeMeSuperSafe'
MGMT_VID=99
IOT_VID=10
HOME_VID=30
GUEST_VID=20
# -------------------------

FLAG="/etc/config/.mesh_done"

start_service() {
  [ -f "$FLAG" ] && return 0

  # BATMAN base
  uci -q delete network.bat0
  uci set network.bat0='interface'
  uci set network.bat0.proto='batadv'
  uci set network.bat0.routing_algo='BATMAN_IV'
  uci set network.bat0.bridge_loop_avoidance='1'
  uci set network.bat0.ap_isolation='0'

  uci -q delete network.meshif
  uci set network.meshif='interface'
  uci set network.meshif.proto='batadv_hardif'
  uci set network.meshif.master='bat0'

  # Mesh iface on radio0
  uci add wireless wifi-iface
  uci set wireless.@wifi-iface[-1].device='radio0'
  uci set wireless.@wifi-iface[-1].mode='mesh'
  uci set wireless.@wifi-iface[-1].mesh_id="$MESHID"
  uci set wireless.@wifi-iface[-1].mesh_fwding='0'
  uci set wireless.@wifi-iface[-1].encryption='sae'
  uci set wireless.@wifi-iface[-1].key="$MESHPASS"
  uci set wireless.@wifi-iface[-1].network='meshif'
  uci set wireless.@wifi-iface[-1].mcast_rate='24000'
  uci set wireless.@wifi-iface[-1].disabled='0'

  mk_mesh_bridge() {
    local name="$1" vid="$2" iptype="$3"
    uci add network device
    uci set network.@device[-1].type='8021q'
    uci set network.@device[-1].ifname='bat0'
    uci set network.@device[-1].vid="$vid"
    uci set network.@device[-1].name="bat0.$vid"

    uci add network device
    uci set network.@device[-1].type='bridge'
    uci set network.@device[-1].name="br-mesh-$name"
    uci add_list network.@device[-1].ports="bat0.$vid"
    uci add_list network.@device[-1].ports="bridge.$vid"

    uci set network.$name.device="br-mesh-$name"
    [ "$iptype" = "dhcp" ] && uci set network.$name.proto='dhcp' || uci set network.$name.proto='none'
  }

  mk_mesh_bridge mgmt  "$MGMT_VID" dhcp
  mk_mesh_bridge iot   "$IOT_VID"  none
  mk_mesh_bridge home  "$HOME_VID" none
  mk_mesh_bridge guest "$GUEST_VID" none

  uci commit

  touch "$FLAG"
  /etc/init.d/network reload >/dev/null 2>&1 || true
  (command -v wifi >/dev/null && wifi reload) 2>/dev/null || true
}
